### ISSUE TITLE
Instructor Feedback

### ISSUE THREAD

**Issue by droxey** [GirugaCode/To-Do-List#1]
Good start, @GirugaCode!

In order to pass this project, you need to make sure to hit the following requirements by EOD today:

* CRUD >=2 Resources and associate them (only one resource and no associations)
* 100% test coverage of all routes (no test coverage)
* A conventional UI using Bootstrap 4 (yours used bootstrap 3.3.7)
* Pushed live to Heroku (add link to `README`)

Thanks!
-d

**Comment by GirugaCode** [comment]
Added all the suggested requirements! Pushed to Github and Heroku!

**Comment by droxey** [comment]
Nice work!!! This is passing now! 👍
